$AppboySDKVersion = '4.3.4'
use_frameworks!


platform :ios, '9.0'

target 'BrazeDesu_Example' do
  pod 'BrazeDesu', "0.1.3"
#  pod 'BrazeDesu', :path => '../'

  target 'BrazeDesu_Tests' do
    inherit! :search_paths
    pod 'BrazeDesu', "0.1.3"
    # pod 'BrazeDesu'
#    pod 'BrazeDesu', :path => '../'

    pod 'Specta'
    pod 'Expecta'
  end
end
